// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Coffee2018.iOS.ViewControllers;
using Coffee2018.ViewModels;

namespace Coffee2018.iOS
{
    public partial class MainViewController : ViewControllerBase<MainViewModel>
    {
        public MainViewController(IntPtr handle) : base(handle)
        {
        }

        protected override void OnViewModelPropertyChanged(string propertyName)
        {
            base.OnViewModelPropertyChanged(propertyName);
        }

        protected override void SetupControls()
        {
            NavigationController.NavigationBar.Hidden = true;
            CoffeeButton.SetTitle("Coucou les cafés !", UIControlState.Normal);
            base.SetupControls();
        }

        protected override void InitializeViewModel()
        {
            ViewModel.NavigateToCoffeeReverseCommand = new Commands.ReverseCommand(NavigateToCoffeeList);
        }

        partial void CoffeeButton_Clicked()
        {
            ViewModel.CoffeeCommand.Execute(null);
        }

        private void NavigateToCoffeeList()
        {
            PerformSegue("CoffeeListSegue", this);
        }
    }
}
